### ISSUE TITLE
Bot don't post Player Disconnect

### ISSUE THREAD

**Issue by HurrycaneBE** [IceEagle132/Farming-Simulator-25-Discord-Bot#4]
Hey Man ;)
after your patch yesterday (giants forum (Farmers Choice))the bot doesn't post player disconnect  anymore.
Also i have received some errors but this seems to be discord.com related (ssl cert not valid means bot ) but webaccess was fine :/

2024-12-17 09:02:38 INFO     discord.gateway Shard ID None has successfully RESUMED session 9e0236e3efd48dc09e6064a5e938ce09.
Error in cleanup_messages: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'discord.com'. (_ssl.c:1007)")]

after restart the bot this evening the errors with ssl was gone but also he dont post players leaves anymore.
Also Playtime will only Show 0m
next : after restart of server the bot also don't post anything anymore - seems dead , but is not crashed in console

**Comment by IceEagle132** [comment]
will look into this

**Comment by IceEagle132** [comment]
Pushed out a new version of the bot.
