### ISSUE TITLE
pinned server updates not updated

### ISSUE THREAD

**Issue by PNSoniX** [IceEagle132/Farming-Simulator-25-Discord-Bot#5]
Bot pins every 30 seconds new Server Updates Post. Update the old one, or deleting the old one would be much better

**Comment by IceEagle132** [comment]
If you looked at the files you would notice that there was a pinned message file made. What you need 2 do is stop the bot delete all the status messages until there is only 1 then copy the ID of that message and put that inside the pinned message file. Then start back up and issue resolved.

**Comment by IceEagle132** [comment]
I pushed Out a new version of the bot.
